remote_theme: geekdevstudy/pixyll

# Site settings
title: Geek Dev Study
email: xxx@example.com
author: Tests
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: "/geekdevstudy.github.io"
url: "http://geekdevstudy.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
